server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: s4jMeRVJomT929sZnCmnIMoKLVWzWKhXWsjkVf4nOix
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true