server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery.locator.enabled: true
      discovery.locator.lower-case-service-id: true

jwt:
  secret: s4jMeRVJomT929sZnCmnIMoKLVWzWKhXWsjkVf4nOix
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true