server:
  port: 8083

spring:
  application:
    name: account_service
  datasource:
    url: jdbc:postgresql://localhost:5434/account-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      properties:
        retry.backoff.ms: 1000